### ISSUE TITLE
Add an "external runner" mode

### ISSUE THREAD

**Issue by josharian** [mvdan/goreduce#18]
I'd like to use goreduce to reduce a test case, but the reproduction of the test case (https://github.com/golang/go/issues/20272) involves some machinery--running the compiler multiple times and checking for identical output. Instead of adding mechanism to goreduce to do that, it'd be nice to have a mode a bit like `git bisect run`.

Here's a rough sketch. I provide an executable to goreduce; it accepts a path argument (file? dir? not sure). goreduce generates a reduction, writes it to disk, and calls my executable with its path. My executable indicates whether it reproduces, or doesn't, or is somehow invalid, with a return code. When minimization is complete, goreduce writes the minimal reduction to disk somewhere, prints the path to it, and exits.

**Comment by mvdan** [comment]
That's how `creduce` works, I think - you give it a command to execute, like a script that runs whatever C compiler of your choice.

I didn't go for that approach, at least by default, because:

* `creduce` doesn't pass any info to such a program, like the input files or packages (we'd want to do that, like you say)
* It limits what `goreduce` can do, e.g. it would not let us take advantage of using `go tool compile` if we ever want to
* To keep things simple as a start

But I'm open to adding this as an option. Maybe something like `-exec=cmdname`, and the command would get the package or file(s) as arguments. And we could use the exit code to know whether or not the error we're reproducing is still there.

**Comment by mvdan** [comment]
Bump @josharian - any thoughts?

Have parked this project for the last month to prioritize other side projects, but will get back to it soon™.

**Comment by josharian** [comment]
> Maybe something like -exec=cmdname, and the command would get the package or file(s) as arguments. And we could use the exit code to know whether or not the error we're reproducing is still there.

That would have been useful at the time I filed this bug. I'm not sure how often it will re-occur. Tough to say. Maybe leave this open until it happens again and/or you feel inspired?

**Comment by mvdan** [comment]
I'll add that flag soon - I wanted to decouple the "backend" somewhat anyway. And this can be interesting to see how well the tool would do for these use cases.

**Comment by mvdan** [comment]
@josharian after thinking about this for a few weeks, I went with removing much of the internal magic and simply exposing the test logic as a shell command.

I believe that should be powerful enough. It's similar to what `creduce` does - you can call a program or script, just like in there. But here you can run inline shell code too, which should keep basic usage simple.
